# -*- coding: utf-8 -*-
"""SE_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bi34LQPjCv0hGkKWeRJreQ3t9PV-veAc
"""

#Quadratic Equation
a=4
b=3
c=2
x=-2

report=a*x**2+b*x+c
print("Predicted weather report:",report)